splash = false

wallpaper {
    monitor = HDMI-A-1
    path = /home/michael/wallpapers/h_1.png
    fit_mode = cover
}

wallpaper {
    monitor = DVI-D-1
    path = /home/michael/wallpapers/v_1.png
    fit_mode = cover
}

wallpaper {
    monitor =
    path = /home/michael/wallpapers/h_1.png
    fit_mode = cover
}
