timeout -1
use_nvram false
extra_kernel_version_strings "linux-hardened,linux-rt-lts,linux-zen,linux-lts,linux-rt,linux",linux-cachyos-bore,linux-cachyos-lts,linux-cachyos-bmq
spoof_osx_version 10.15
banner black.png
banner_scale fillscreen
use_graphics_for linux
