# Enable or Disable Triggers (elogind)
enable no

# CPU Undervolting
undervolt 0 "CPU" -65
undervolt 1 "GPU" 0
undervolt 2 "CPU Cache" -65
undervolt 3 "System Agent" 0
undervolt 4 "Analog I/O" 0

# Power Limits Alteration
power package 35 28

interval 5000

daemon undervolt:once
daemon power
daemon tjoffset
